# Generated by Django 2.2.14 on 2020-08-13 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_bookreview_gamereview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookReview',
        ),
    ]
