# Generated by Django 2.2.14 on 2020-08-13 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200813_2009'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameReview',
        ),
    ]
