# Generated by Django 2.2.14 on 2020-08-13 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_delete_gamereview'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameReview',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.Post')),
                ('coverArt', models.ImageField(blank=True, null=True, upload_to='')),
                ('intro', models.TextField()),
                ('graphics', models.TextField()),
                ('story', models.TextField()),
                ('gameplay', models.TextField()),
                ('conclusion', models.TextField()),
            ],
            bases=('blog.post',),
        ),
    ]
