# Generated by Django 2.2.14 on 2020-08-13 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_gamereview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameReview',
        ),
    ]
